# $FreeBSD$

freebsd_instance:
  image_family: freebsd-14-0-snap

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  timeout_in: 90m
  install_script:
  - pkg install -qy strongswan
  # Uncomment the following lines and add the failing test in case of a
  # failing task
  debug_script:
  - kyua debug -k $CIRRUS_WORKING_DIR/Kyuafile tests/freebsd/rc_script/rc_script:vici
  #test_script:
  #- kyua test -k $CIRRUS_WORKING_DIR/Kyuafile
