#!/usr/libexec/atf-sh

: ${TMPDIR=/tmp}

. $(atf_get_srcdir)/../../../scripts/utils.subr

atf_test_case stroke cleanup

stroke_head()
{
	atf_set descr "Test stroke rc script"
	atf_set require.user root
}

stroke_body()
{
	sst_init

	cp $(atf_get_srcdir)/files/moon/etc/rc.d/strongswan ${TMPDIR}/strongswan
	jexec moon mv ${TMPDIR}/strongswan /usr/local/etc/rc.d
	jexec moon chmod 0555 /usr/local/etc/rc.d/strongswan

	jexec moon sysrc strongswan_enable=YES
	jexec moon sysrc strongswan_interface=stroke

	# start (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check -s not-exit:0 \
		-e match:"strongswan already running?" \
		jexec moon service strongswan start
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# start (stopped)
	atf_check \
		-o match:"Starting strongswan." \
		-e match:"Starting strongSwan" \
		jexec moon service strongswan start
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# stop (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-o match:"Stopping strongswan." \
		-o match:"Waiting for PIDS" \
		jexec moon service strongswan stop
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# stop (stopped)
	atf_check -s not-exit:0 \
		-e match:"strongswan not running?" \
		jexec moon service strongswan stop
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# restart (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-o match:"Stopping strongswan." \
		-o match:"Waiting for PIDS" \
		-o match:"Starting strongswan." \
		-e match:"Starting strongSwan" \
		jexec moon service strongswan restart
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# restart (stopped)
	atf_check \
		-o match:"Starting strongswan." \
		-e match:"Starting strongSwan" \
		jexec moon service strongswan restart
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# status (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-o match:"Security Associations" \
		jexec moon service strongswan status
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# status (stopped)
	atf_check -s not-exit:0 \
		jexec moon service strongswan status
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# statusall (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-o match:"Status of IKE charon daemon" \
		-o match:"Connections" \
		-o match:"Security Associations" \
		jexec moon service strongswan statusall
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# statusall (stopped)
	atf_check -s not-exit:0 \
		jexec moon service strongswan statusall
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# reload (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-e match:"Reloading strongSwan IPsec configuration..." \
		jexec moon service strongswan reload
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# reload (stopped)
	atf_check -s not-exit:0 \
		-e match:"starter is not running" \
		jexec moon service strongswan reload
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# respawn charon process
	jexec moon service strongswan start > /dev/null 2>&1 || true
	jexec moon sleep 1
	charon_pid=$(jexec moon cat /var/run/charon.pid)
	jexec moon kill -9 $charon_pid
	jexec moon sleep 5
	atf_check \
		-o match:"/usr/local/libexec/ipsec/charon" \
		jexec moon ps auxww
	jexec moon service strongswan stop > /dev/null 2>&1 || true
}

stroke_cleanup()
{
	sst_cleanup
}

atf_test_case vici cleanup

vici_head()
{
	atf_set descr "Test VICI rc script"
	atf_set require.user root
}

vici_body()
{
	sst_init

	cp $(atf_get_srcdir)/files/moon/etc/rc.d/strongswan ${TMPDIR}/strongswan
	jexec moon mv ${TMPDIR}/strongswan /usr/local/etc/rc.d
	jexec moon service strongswan stop > /dev/null 2>&1
	jexec moon service strongswan stop > /dev/null 2>&1
	jexec moon service strongswan stop > /dev/null 2>&1
	jexec moon service strongswan stop > /dev/null 2>&1
	jexec moon service strongswan stop > /dev/null 2>&1
	jexec moon service strongswan stop > /dev/null 2>&1
	jexec moon chmod 0555 /usr/local/etc/rc.d/strongswan

	cp $(atf_get_srcdir)/files/moon/etc/swanctl/conf.d/dummy.conf \
		${TMPDIR}/dummy.conf
	jexec moon mv ${TMPDIR}/dummy.conf /usr/local/etc/swanctl/conf.d

	jexec moon sysrc strongswan_enable=YES
	jexec moon sysrc strongswan_interface=VICI

	# start (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check -s not-exit:0 \
		-e match:"strongswan already running?" \
		jexec moon service strongswan start
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# start (stopped)
	atf_check \
		-o match:"Starting strongswan." \
		-o match:"successfully loaded [[:digit:]]+ connections" \
		-o match:"authorities found" \
		-o match:"pools found" \
		jexec moon service strongswan start
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# stop (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-o match:"Stopping strongswan." \
		-o match:"Waiting for PIDS" \
		jexec moon service strongswan stop
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# stop (stopped)
	atf_check -s not-exit:0 \
		-e match:"strongswan not running?" \
		jexec moon service strongswan stop
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# restart (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-o match:"Stopping strongswan." \
		-o match:"Waiting for PIDS" \
		-o match:"Starting strongswan." \
		-o match:"successfully loaded [[:digit:]]+ connections" \
		-o match:"authorities found" \
		-o match:"pools found" \
		jexec moon service strongswan restart
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# restart (stopped)
	atf_check \
		-e match:"strongswan not running?" \
		-o match:"Starting strongswan." \
		-o match:"successfully loaded [[:digit:]]+ connections" \
		-o match:"authorities found" \
		-o match:"pools found" \
		jexec moon service strongswan restart
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# status (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-o match:"uptime" \
		-o match:"worker threads" \
		-o match:"loaded plugins" \
		jexec moon service strongswan status
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# status (stopped)
	atf_check -s not-exit:0 \
		-e match:"strongswan not running?" \
		jexec moon service strongswan status
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# statusall (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-o match:"uptime" \
		-o match:"worker threads" \
		-o match:"loaded plugins" \
		jexec moon service strongswan statusall
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# statusall (stopped)
	atf_check -s not-exit:0 \
		-e match:"strongswan not running?" \
		jexec moon service strongswan statusall
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# reload (started)
	jexec moon service strongswan start > /dev/null 2>&1 || true
	atf_check \
		-o match:"successfully loaded [[:digit:]]+ connections" \
		-o match:"authorities found" \
		-o match:"pools found" \
		jexec moon service strongswan reload
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# reload (stopped)
	atf_check -s not-exit:0 \
		-e match:"strongswan not running?" \
		jexec moon service strongswan reload
	jexec moon service strongswan stop > /dev/null 2>&1 || true

	# respawn charon process
	#
	# NB: This implies that the daemon gets supervised and
	# *restarted*.  While this was true for the old stroke, it is
	# not true for vici as it is at the moment.
	# A user switching from stoke to vici would expect this
	# behavior, as well as users switching from strongswan on
	# Linux-based systems; charon-systemd supervises the process
	# and respawns accordingly.
	# While, this should be up for debate, I guess it is one of the
	# reasons why some users are still reluctant to switch to vici
	# (nobody wants to loose their VPN connections).
	jexec moon service strongswan start > /dev/null 2>&1 || true
	jexec moon sleep 1
	charon_pid=$(jexec moon cat /var/run/charon.pid)
	jexec moon kill -9 $charon_pid
	jexec moon sleep 2 # daemon(8) restarts after 1 second
	atf_check \
		-o match:"/usr/local/libexec/ipsec/charon" \
		jexec moon ps auxww
	jexec moon service strongswan stop > /dev/null 2>&1 || true
}

vici_cleanup()
{
	sst_cleanup
}

atf_init_test_cases()
{
	atf_add_test_case stroke
	atf_add_test_case vici
}
